MY_AMRNB_ENC_LIST := codecs_v2/audio/gsm_amr/amr_nb/enc/
LOCAL_SRC_FILES := \
	$(MY_AMRNB_ENC_LIST)src/amrencode.cpp \
 	$(MY_AMRNB_ENC_LIST)src/autocorr.cpp \
 	$(MY_AMRNB_ENC_LIST)src/c1035pf.cpp \
 	$(MY_AMRNB_ENC_LIST)src/c2_11pf.cpp \
 	$(MY_AMRNB_ENC_LIST)src/c2_9pf.cpp \
 	$(MY_AMRNB_ENC_LIST)src/c3_14pf.cpp \
 	$(MY_AMRNB_ENC_LIST)src/c4_17pf.cpp \
 	$(MY_AMRNB_ENC_LIST)src/c8_31pf.cpp \
 	$(MY_AMRNB_ENC_LIST)src/calc_cor.cpp \
 	$(MY_AMRNB_ENC_LIST)src/calc_en.cpp \
 	$(MY_AMRNB_ENC_LIST)src/cbsearch.cpp \
 	$(MY_AMRNB_ENC_LIST)src/cl_ltp.cpp \
 	$(MY_AMRNB_ENC_LIST)src/cod_amr.cpp \
 	$(MY_AMRNB_ENC_LIST)src/convolve.cpp \
 	$(MY_AMRNB_ENC_LIST)src/cor_h.cpp \
 	$(MY_AMRNB_ENC_LIST)src/cor_h_x.cpp \
 	$(MY_AMRNB_ENC_LIST)src/cor_h_x2.cpp \
 	$(MY_AMRNB_ENC_LIST)src/corrwght_tab.cpp \
 	$(MY_AMRNB_ENC_LIST)src/div_32.cpp \
 	$(MY_AMRNB_ENC_LIST)src/dtx_enc.cpp \
 	$(MY_AMRNB_ENC_LIST)src/enc_lag3.cpp \
 	$(MY_AMRNB_ENC_LIST)src/enc_lag6.cpp \
 	$(MY_AMRNB_ENC_LIST)src/enc_output_format_tab.cpp \
 	$(MY_AMRNB_ENC_LIST)src/ets_to_if2.cpp \
 	$(MY_AMRNB_ENC_LIST)src/ets_to_wmf.cpp \
 	$(MY_AMRNB_ENC_LIST)src/g_adapt.cpp \
 	$(MY_AMRNB_ENC_LIST)src/g_code.cpp \
 	$(MY_AMRNB_ENC_LIST)src/g_pitch.cpp \
 	$(MY_AMRNB_ENC_LIST)src/gain_q.cpp \
 	$(MY_AMRNB_ENC_LIST)src/hp_max.cpp \
 	$(MY_AMRNB_ENC_LIST)src/inter_36.cpp \
 	$(MY_AMRNB_ENC_LIST)src/inter_36_tab.cpp \
 	$(MY_AMRNB_ENC_LIST)src/l_abs.cpp \
 	$(MY_AMRNB_ENC_LIST)src/l_comp.cpp \
 	$(MY_AMRNB_ENC_LIST)src/l_extract.cpp \
 	$(MY_AMRNB_ENC_LIST)src/l_negate.cpp \
 	$(MY_AMRNB_ENC_LIST)src/lag_wind.cpp \
 	$(MY_AMRNB_ENC_LIST)src/lag_wind_tab.cpp \
 	$(MY_AMRNB_ENC_LIST)src/levinson.cpp \
 	$(MY_AMRNB_ENC_LIST)src/lpc.cpp \
 	$(MY_AMRNB_ENC_LIST)src/ol_ltp.cpp \
 	$(MY_AMRNB_ENC_LIST)src/p_ol_wgh.cpp \
 	$(MY_AMRNB_ENC_LIST)src/pitch_fr.cpp \
 	$(MY_AMRNB_ENC_LIST)src/pitch_ol.cpp \
 	$(MY_AMRNB_ENC_LIST)src/pre_big.cpp \
 	$(MY_AMRNB_ENC_LIST)src/pre_proc.cpp \
 	$(MY_AMRNB_ENC_LIST)src/prm2bits.cpp \
 	$(MY_AMRNB_ENC_LIST)src/q_gain_c.cpp \
 	$(MY_AMRNB_ENC_LIST)src/q_gain_p.cpp \
 	$(MY_AMRNB_ENC_LIST)src/qgain475.cpp \
 	$(MY_AMRNB_ENC_LIST)src/qgain795.cpp \
 	$(MY_AMRNB_ENC_LIST)src/qua_gain.cpp \
 	$(MY_AMRNB_ENC_LIST)src/s10_8pf.cpp \
 	$(MY_AMRNB_ENC_LIST)src/set_sign.cpp \
 	$(MY_AMRNB_ENC_LIST)src/sid_sync.cpp \
 	$(MY_AMRNB_ENC_LIST)src/sp_enc.cpp \
 	$(MY_AMRNB_ENC_LIST)src/spreproc.cpp \
 	$(MY_AMRNB_ENC_LIST)src/spstproc.cpp \
 	$(MY_AMRNB_ENC_LIST)src/ton_stab.cpp \
 	$(MY_AMRNB_ENC_LIST)src/vad1.cpp \
