/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ntdn_voiceutil_service_CVoiceService */

#ifndef _SOUND_EFFECT_JNI_H_
#define _SOUND_EFFECT_JNI_H_
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ntdn_voiceutil_service_CVoiceService
 * Method:    init
 * Signature: ()I
 */JNIEXPORT jint JNICALL Java_ntdn_voiceutil_service_CVoiceService_init(JNIEnv *,
		jobject, jstring);
/*
 * Class:     ntdn_voiceutil_service_CVoiceService
 * Method:    destroy
 * Signature: ()V
 */JNIEXPORT jint JNICALL Java_ntdn_voiceutil_service_CVoiceService_destroy(
		JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_ntdn_voiceutil_service_CVoiceService_setSampleRate(
		JNIEnv* pEnv, jobject pThis, jint sampleRate);

JNIEXPORT void JNICALL Java_ntdn_voiceutil_service_CVoiceService_setChannel(
		JNIEnv* pEnv, jobject pThis, jint channel);
/*
 * Class:     ntdn_voiceutil_service_CVoiceService
 * Method:    startRecord
 * Signature: ()V
 */JNIEXPORT jint JNICALL Java_ntdn_voiceutil_service_CVoiceService_startRecord(
		JNIEnv *, jobject);
/*
 * Class:     ntdn_voiceutil_service_CVoiceService
 * Method:    stopRecord
 * Signature: ()V
 */JNIEXPORT jint JNICALL Java_ntdn_voiceutil_service_CVoiceService_stopRecord(
		JNIEnv *, jobject);
/*
 * Class:     ntdn_voiceutil_service_CVoiceService
 * Method:    startPlayer
 * Signature: ()V
 */JNIEXPORT jint JNICALL Java_ntdn_voiceutil_service_CVoiceService_startPlayer(
		JNIEnv *, jobject);
/*
 * Class:     ntdn_voiceutil_service_CVoiceService
 * Method:    stopPlayer
 * Signature: ()V
 */JNIEXPORT jint JNICALL Java_ntdn_voiceutil_service_CVoiceService_stopPlayer(
		JNIEnv *, jobject);
/*
 * Class:     ntdn_voiceutil_service_CVoiceService
 * Method:    initEffectLib
 * Signature: (O)I
 */JNIEXPORT jint JNICALL Java_ntdn_voiceutil_service_CVoiceService_initEffectLib(
		JNIEnv *, jobject, jobject);
/*
 * Class:     ntdn_voiceutil_service_CVoiceService
 * Method:    destroyEffect
 * Signature: ()V
 */JNIEXPORT jint JNICALL Java_ntdn_voiceutil_service_CVoiceService_destroyEffectLib(
		JNIEnv *, jobject);
/*
 * Class:     ntdn_voiceutil_service_CVoiceService
 * Method:    playEffect
 * Signature: (I)V
 */JNIEXPORT jint JNICALL Java_ntdn_voiceutil_service_CVoiceService_playEffect(
		JNIEnv *, jobject, jint);

/*
 * Class:     ntdn_voiceutil_service_CVoiceService
 * Method:    saveFile
 * Signature: (I)V
 */
jint Java_ntdn_voiceutil_service_CVoiceService_saveFile(JNIEnv* pEnv,
		jobject pThis, jstring, jint, jint);

/*
 * Class:     ntdn_voiceutil_service_CVoiceService
 * Method:    playCustomEffect
 * Signature: (ZZZZ)V
 */

JNIEXPORT void JNICALL Java_ntdn_voiceutil_service_CVoiceService_playCustomEffect(
		JNIEnv *, jobject, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     ntdn_voiceutil_service_CVoiceService
 * Method:    prepareSoundTouchEffect
 * Signature: (DDD)V
 */

JNIEXPORT void JNICALL Java_ntdn_voiceutil_service_CVoiceService_prepareSoundTouchEffect(
		JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     ntdn_voiceutil_service_CVoiceService
 * Method:    prepareBackgroundEffect
 * Signature: (Ljava/lang/String;DZ)V
 */

JNIEXPORT void JNICALL Java_ntdn_voiceutil_service_CVoiceService_prepareBackgroundEffect(
		JNIEnv *, jobject, jstring, jdouble, jboolean, jboolean);

/*
 * Class:     ntdn_voiceutil_service_CVoiceService
 * Method:    prepareReverbEffect
 * Signature: (DDDDDDDD)V
 */

JNIEXPORT void JNICALL Java_ntdn_voiceutil_service_CVoiceService_prepareReverbEffect(
		JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble,
		jdouble, jdouble);

/*
 * Class:     ntdn_voiceutil_service_CVoiceService
 * Method:    prepareEchoReverb
 * Signature: (DD)V
 */

JNIEXPORT void JNICALL Java_ntdn_voiceutil_service_CVoiceService_prepareEchoReverb(
		JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
