MY_AMRNB_COMMON_LIST := codecs_v2/audio/gsm_amr/amr_nb/common/
LOCAL_SRC_FILES += \
	$(MY_AMRNB_COMMON_LIST)src/add.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/az_lsp.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/bitno_tab.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/bitreorder_tab.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/c2_9pf_tab.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/div_s.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/gains_tbl.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/gc_pred.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/get_const_tbls.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/gmed_n.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/grid_tbl.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/gray_tbl.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/int_lpc.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/inv_sqrt.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/inv_sqrt_tbl.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/l_shr_r.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/log2.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/log2_norm.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/log2_tbl.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/lsfwt.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/lsp.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/lsp_az.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/lsp_lsf.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/lsp_lsf_tbl.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/lsp_tab.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/mult_r.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/norm_l.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/norm_s.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/overflow_tbl.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/ph_disp_tab.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/pow2.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/pow2_tbl.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/pred_lt.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/q_plsf.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/q_plsf_3.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/q_plsf_3_tbl.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/q_plsf_5.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/q_plsf_5_tbl.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/qua_gain_tbl.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/reorder.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/residu.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/round.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/shr.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/shr_r.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/sqrt_l.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/sqrt_l_tbl.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/sub.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/syn_filt.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/weight_a.cpp \
 	$(MY_AMRNB_COMMON_LIST)src/window_tab.cpp
