/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vng_wmb_service_EchoEffect */

#ifndef _ECHO_EFFECT_H_
#define _ECHO_EFFECT_H_
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vng_wmb_service_EchoEffect
 * Method:    init
 * Signature: (DDDDDDDD)V
 */

JNIEXPORT void JNICALL Java_vng_wmb_service_EchoEffect_init(JNIEnv *, jobject);

/*
 * Class:     vng_wmb_service_EchoEffect
 * Method:    initProcess
 * Signature: ()V
 */

JNIEXPORT void JNICALL Java_vng_wmb_service_EchoEffect_initProcess(JNIEnv *,
		jobject, jdouble, jdouble);

/*
 * Class:     vng_wmb_service_EchoEffect
 * Method:    destroy
 * Signature: ()V
 */

JNIEXPORT void JNICALL Java_vng_wmb_service_EchoEffect_destroy(JNIEnv *,
		jobject);

int processBlockForEcho(short** playerBuffer, int size);

#ifdef __cplusplus
}
#endif
#endif
