/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vng_wmb_service_ReverbEffect */

#ifndef _Included_vng_wmb_service_ReverbEffect
#define _Included_vng_wmb_service_ReverbEffect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vng_wmb_service_ReverbEffect
 * Method:    init
 * Signature: (DDDDDDDD)V
 */

JNIEXPORT void JNICALL Java_vng_wmb_service_ReverbEffect_init(JNIEnv *, jobject,
		jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     vng_wmb_service_ReverbEffect
 * Method:    destroy
 * Signature: ()V
 */

JNIEXPORT void JNICALL Java_vng_wmb_service_ReverbEffect_destroy(JNIEnv *,
		jobject);

int processBlock(short** playerBuffer, int nSamples);

#ifdef __cplusplus
}
#endif
#endif
