/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vng_wmb_service_ReverbEffect */

#ifndef _REVERBEFFECT_H_
#define _REVERBEFFECT_H_
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vng_wmb_service_ReverbEffect
 * Method:    init
 * Signature: (DDDDDDDD)V
 */

JNIEXPORT void JNICALL Java_vng_wmb_service_ReverbEffect_init(JNIEnv *,
		jobject);

/*
 * Class:     vng_wmb_service_ReverbEffect
 * Method:    initProcess
 * Signature: ()V
 */

JNIEXPORT void JNICALL Java_vng_wmb_service_ReverbEffect_initProcess(JNIEnv *,
		jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble,
		jdouble);

/*
 * Class:     vng_wmb_service_ReverbEffect
 * Method:    destroy
 * Signature: ()V
 */

JNIEXPORT void JNICALL Java_vng_wmb_service_ReverbEffect_destroy(JNIEnv *,
		jobject);

int processBlockForReverb(short** playerBuffer, int size);

#ifdef __cplusplus
}
#endif
#endif
