/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vng_wmb_service_SoundEffect */

#ifndef _SOUND_EFFECT_JNI_H_
#define _SOUND_EFFECT_JNI_H_
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     vng_wmb_service_SoundEffect
 * Method:    init
 * Signature: ()I
 */JNIEXPORT jint JNICALL Java_vng_wmb_service_SoundEffect_init(JNIEnv *,
		jobject, jstring);
/*
 * Class:     vng_wmb_service_SoundEffect
 * Method:    destroy
 * Signature: ()V
 */JNIEXPORT jint JNICALL Java_vng_wmb_service_SoundEffect_destroy(JNIEnv *,
		jobject);
/*
 * Class:     vng_wmb_service_SoundEffect
 * Method:    startRecord
 * Signature: ()V
 */JNIEXPORT jint JNICALL Java_vng_wmb_service_SoundEffect_startRecord(JNIEnv *,
		jobject);
/*
 * Class:     vng_wmb_service_SoundEffect
 * Method:    stopRecord
 * Signature: ()V
 */JNIEXPORT jint JNICALL Java_vng_wmb_service_SoundEffect_stopRecord(JNIEnv *,
		jobject);
/*
 * Class:     vng_wmb_service_SoundEffect
 * Method:    startPlayer
 * Signature: ()V
 */JNIEXPORT jint JNICALL Java_vng_wmb_service_SoundEffect_startPlayer(JNIEnv *,
		jobject);
/*
 * Class:     vng_wmb_service_SoundEffect
 * Method:    stopPlayer
 * Signature: ()V
 */JNIEXPORT jint JNICALL Java_vng_wmb_service_SoundEffect_stopPlayer(JNIEnv *,
		jobject);
/*
 * Class:     vng_wmb_service_SoundEffect
 * Method:    initEffectLib
 * Signature: (O)I
 */JNIEXPORT jint JNICALL Java_vng_wmb_service_SoundEffect_initEffectLib(JNIEnv *,
		jobject, jobject);
/*
 * Class:     vng_wmb_service_SoundEffect
 * Method:    destroyEffect
 * Signature: ()V
 */JNIEXPORT jint JNICALL Java_vng_wmb_service_SoundEffect_destroyEffectLib(
		JNIEnv *, jobject);
/*
 * Class:     vng_wmb_service_SoundEffect
 * Method:    playEffect
 * Signature: (I)V
 */JNIEXPORT jint JNICALL Java_vng_wmb_service_SoundEffect_playEffect(JNIEnv *,
		jobject, jint);
/*
 * Class:     vng_wmb_service_SoundEffect
 * Method:    processAndWriteToAmr
 * Signature: (I)V
 */JNIEXPORT jint JNICALL Java_vng_wmb_service_SoundEffect_processAndWriteToAmr(
		JNIEnv *, jobject, jint);
/*
 * Class:     vng_wmb_service_SoundEffect
 * Method:    processAndWriteToMp3
 * Signature: (I)V
 */JNIEXPORT jint JNICALL Java_vng_wmb_service_SoundEffect_processAndWriteToMp3(
		JNIEnv *, jobject, jint);

/*
 * Class:     vng_wmb_service_SoundEffect
 * Method:    playCustomEffect
 * Signature: (ZZZZ)V
 */

JNIEXPORT void JNICALL Java_vng_wmb_service_SoundEffect_playCustomEffect(
		JNIEnv *, jobject, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     vng_wmb_service_SoundEffect
 * Method:    prepareSoundTouchEffect
 * Signature: (DDD)V
 */

JNIEXPORT void JNICALL Java_vng_wmb_service_SoundEffect_prepareSoundTouchEffect(
		JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     vng_wmb_service_SoundEffect
 * Method:    prepareBackgroundEffect
 * Signature: (Ljava/lang/String;DZ)V
 */

JNIEXPORT void JNICALL Java_vng_wmb_service_SoundEffect_prepareBackgroundEffect(
		JNIEnv *, jobject, jstring, jdouble, jboolean, jboolean);

/*
 * Class:     vng_wmb_service_SoundEffect
 * Method:    prepareReverbEffect
 * Signature: (DDDDDDDD)V
 */

JNIEXPORT void JNICALL Java_vng_wmb_service_SoundEffect_prepareReverbEffect(
		JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble,
		jdouble, jdouble);

/*
 * Class:     vng_wmb_service_SoundEffect
 * Method:    prepareEchoReverb
 * Signature: (DD)V
 */

JNIEXPORT void JNICALL Java_vng_wmb_service_SoundEffect_prepareEchoReverb(
		JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
