/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ntdn_voiceutil_manager_CSoundManager */

#ifndef _SOUND_EFFECT_JNI_H_
#define _SOUND_EFFECT_JNI_H_
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ntdn_voiceutil_manager_CSoundManager
 * Method:    init
 * Signature: ()I
 */JNIEXPORT jint JNICALL Java_ntdn_voiceutil_manager_CSoundManager_init(JNIEnv *,
		jobject, jstring);
/*
 * Class:     ntdn_voiceutil_manager_CSoundManager
 * Method:    destroy
 * Signature: ()V
 */JNIEXPORT jint JNICALL Java_ntdn_voiceutil_manager_CSoundManager_destroy(
		JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_ntdn_voiceutil_manager_CSoundManager_setSampleRate(
		JNIEnv* pEnv, jobject pThis, jint sampleRate);

JNIEXPORT void JNICALL Java_ntdn_voiceutil_manager_CSoundManager_setChannel(
		JNIEnv* pEnv, jobject pThis, jint channel);
/*
 * Class:     ntdn_voiceutil_manager_CSoundManager
 * Method:    startRecord
 * Signature: ()V
 */JNIEXPORT jint JNICALL Java_ntdn_voiceutil_manager_CSoundManager_startRecord(
		JNIEnv *, jobject);
/*
 * Class:     ntdn_voiceutil_manager_CSoundManager
 * Method:    stopRecord
 * Signature: ()V
 */JNIEXPORT jint JNICALL Java_ntdn_voiceutil_manager_CSoundManager_stopRecord(
		JNIEnv *, jobject);
/*
 * Class:     ntdn_voiceutil_manager_CSoundManager
 * Method:    startPlayer
 * Signature: ()V
 */JNIEXPORT jint JNICALL Java_ntdn_voiceutil_manager_CSoundManager_startPlayer(
		JNIEnv *, jobject);
/*
 * Class:     ntdn_voiceutil_manager_CSoundManager
 * Method:    stopPlayer
 * Signature: ()V
 */JNIEXPORT jint JNICALL Java_ntdn_voiceutil_manager_CSoundManager_stopPlayer(
		JNIEnv *, jobject);
/*
 * Class:     ntdn_voiceutil_manager_CSoundManager
 * Method:    initEffectLib
 * Signature: (O)I
 */JNIEXPORT jint JNICALL Java_ntdn_voiceutil_manager_CSoundManager_initEffectLib(
		JNIEnv *, jobject, jobject);
/*
 * Class:     ntdn_voiceutil_manager_CSoundManager
 * Method:    destroyEffect
 * Signature: ()V
 */JNIEXPORT jint JNICALL Java_ntdn_voiceutil_manager_CSoundManager_destroyEffectLib(
		JNIEnv *, jobject);
/*
 * Class:     ntdn_voiceutil_manager_CSoundManager
 * Method:    playEffect
 * Signature: (I)V
 */JNIEXPORT jint JNICALL Java_ntdn_voiceutil_manager_CSoundManager_playEffect(
		JNIEnv *, jobject, jint);

/*
 * Class:     ntdn_voiceutil_manager_CSoundManager
 * Method:    saveFile
 * Signature: (I)V
 */
jint Java_ntdn_voiceutil_manager_CSoundManager_saveFile(JNIEnv* pEnv,
		jobject pThis, jstring, jint, jint);

/*
 * Class:     ntdn_voiceutil_manager_CSoundManager
 * Method:    playCustomEffect
 * Signature: (ZZZZ)V
 */

JNIEXPORT void JNICALL Java_ntdn_voiceutil_manager_CSoundManager_playCustomEffect(
		JNIEnv *, jobject, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     ntdn_voiceutil_manager_CSoundManager
 * Method:    prepareSoundTouchEffect
 * Signature: (DDD)V
 */

JNIEXPORT void JNICALL Java_ntdn_voiceutil_manager_CSoundManager_prepareSoundTouchEffect(
		JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     ntdn_voiceutil_manager_CSoundManager
 * Method:    prepareBackgroundEffect
 * Signature: (Ljava/lang/String;DZ)V
 */

JNIEXPORT void JNICALL Java_ntdn_voiceutil_manager_CSoundManager_prepareBackgroundEffect(
		JNIEnv *, jobject, jstring, jdouble, jboolean, jboolean);

/*
 * Class:     ntdn_voiceutil_manager_CSoundManager
 * Method:    prepareReverbEffect
 * Signature: (DDDDDDDD)V
 */

JNIEXPORT void JNICALL Java_ntdn_voiceutil_manager_CSoundManager_prepareReverbEffect(
		JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble,
		jdouble, jdouble);

/*
 * Class:     ntdn_voiceutil_manager_CSoundManager
 * Method:    prepareEchoReverb
 * Signature: (DD)V
 */

JNIEXPORT void JNICALL Java_ntdn_voiceutil_manager_CSoundManager_prepareEchoReverb(
		JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
